g.mapleader = ' '
o.number = true
o.relativenumber = true
o.shiftwidth = 2
o.tabstop = 2
o.expandtab = true
o.smartindent = true
o.showmatch = true
o.incsearch = true
o.ignorecase = true
wo.wrap = false
